# Site settings
title: 老武博客
email: me@zhengjunwu.com
description: > # this means to ignore newlines until "baseurl:"
  老武博客，一个码农的个人空间。
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.zhengjunwu.com" # the base hostname & protocol for your site
github_username:  lao5net

# Build settings
markdown: kramdown
